version: '3.3'

services:
  swarmpit-app:
    image: swarmpit/swarmpit:1.9
    environment:
      - SWARMPIT_DB=http://swarmpit-db:5984
      - SWARMPIT_INFLUXDB=http://swarmpit-influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4GB
          cpus: '2'
      placement:
        constraints:
          - node.role == manager

  swarmpit-db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4GB
          cpus: '2'
      placement:
        constraints:
          - node.role == manager

  swarmpit-influxdb:
    image: influxdb:1.8
    volumes:
      - influx-data:/var/lib/influxdb
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4GB
          cpus: '2'
      placement:
        constraints:
          - node.role == manager

  swarmpit-agent:
    image: swarmpit/agent:2.2
    environment:
      - DOCKER_API_VERSION=1.35
      - HEALTH_CHECK_ENDPOINT=http://swarmpit-app:8080/version
      - EVENT_ENDPOINT=http://swarmpit-app:8080/events
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        limits:
          memory: 4GB
          cpus: '2'

networks:
  net:
    driver: overlay

volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
