apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Loki  

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus-prometheus:9090
  isDefault: true
  version: 1
  editable: true
- name: Loki
  type: loki
  access: proxy
  url: http://prometheus-loki:3100
  isDefault: false
  version: 1
  editable: true
