version: '3.2'

services:
  portainer-agent:
    image: portainer/agent:2.16.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          memory: 4GB
          cpus: '2'
      placement:
        constraints: [node.platform.os == linux]

  portainer-portainer:
    image: portainer/portainer-ce:2.16.2
    # command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify --sslcert /run/secrets/portainer.sslcert --sslkey /run/secrets/portainer.sslkey
    command: -H tcp://tasks.portainer-agent:9001
    ports:
      # - "9443:9443"
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 4GB
          cpus: '2'
      placement:
        constraints: [node.role == manager]
    # secrets:
    #     - portainer.sslcert
    #     - portainer.sslkey

networks:
  net:
    driver: overlay
    attachable: true
    
volumes:
  portainer_data:

# secrets:
#   portainer.sslcert:
#     file: secrets/certbundle.pem
#   portainer.sslkey:
#     file: secrets/certkey.pem
