global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.prometheus-node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.prometheus-dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.prometheus-cadvisor'
      type: 'A'
      port: 8080
